version: '3'

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: cusosnestjs-app
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
    depends_on:
      - db
  db:
    build: .docker/mysql
    container_name: cusosnestjs-db
    restart: always
    command: --lower_case_table_names=0
    tty: true
    ports:
      - '3306:3306'
    volumes:
      - ./docker/dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: 'devtraining'
  dbtest:
    build: .docker/mysql
    container_name: cusosnestjs-dbtest
    restart: always
    command: --lower_case_table_names=0
    tty: true
    ports:
      - '5433:3306'
    volumes:
      - ./docker/dbdatatest:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: 'devtrainingtest'
